rootProject.name= "chal"

include (":app")
include (":main:resources")
include(":main:splash")
include(":ui:typefaces")
include(":network")
include(":firebase:auth")
include(":account:validation")
include(":ui:base-vm")
include(":ui:base-fragment")
include(":main:navigation")
include(":account:login")
include(":helper:fragment")
include(":main:activity")
include(":account:forgot-password")
include(":ui:shared-layout")
include(":account:sign-up")
include(":account:create-account")
include(":shared-preference:create")
include(":shared-preference:fetch")
include(":shared-preference:remove")
include(":firebase:storage")
include(":firebase:database")
include(":data:account-info")
include(":main:news-feed")
include(":helper:constants")
