rootProject.name= "chal"

include (":app")
include (":main:resources")
include(":main:splash")
include(":ui:typefaces")
include(":network")
include(":firebase:auth")
include(":account:validation")
include(":ui:base-vm")
include(":ui:base-fragment")
include(":main:navigation")
include(":account:login")
include(":helper:fragment")
include(":main:activity")
