rootProject.name= "chal"

include(":account:create-account")
include(":account:forgot-password")
include(":account:login")
include(":account:sign-up")
include(":account:validation")
include (":app")
include(":challenge:detail")
include(":challenge:helper")
include(":challenge:list")
include(":challenge-manager")
include(":data:account-info")
include(":data:alert")
include(":data:challenges")
include(":data:post")
include(":firebase:auth")
include(":firebase:storage")
include(":firebase:realtime-database:create")
include(":firebase:realtime-database:fetch")
include(":firebase:realtime-database:delete")
include(":helper:constants")
include(":helper:fragment")
include(":helper:image")
include(":main:activity")
include(":main:navigation")
include(":main:news-feed")
include (":main:resources")
include(":main:splash")
include(":main:upload-progress")
include(":more")
include(":network")
include(":profile")
include(":shared-preference:create")
include(":shared-preference:fetch")
include(":shared-preference:remove")
include(":ui:base-fragment")
include(":ui:base-vm")
include(":ui:shared-layout")
include(":ui:typefaces")